version: '{branch}-{build}'
image: Visual Studio 2017
clone_depth: 5
clone_script:
- cmd: |
    pwd
    git clone -q --depth=5 --branch=v2.3.2 git://github.com/plumed/plumed2.git C:\projects\plumed2
build_script:
- cmd: |
    cd C:\projects\plumed2
    set mw=C:\msys64\usr\bin
    set PATH=%mw%;%PATH%
    rem dir /s %mw%
    g++ -v
    bash ./configure --disable-shared LDFLAGS="-static -s" --prefix=/c/projects/plumed2/plumed2-win-build
    make -j2
    make install
test_script:
- cmd: |
    set PATH=%CD%/plumed2-win-build/bin;%PATH%
    cd regtest
    make
artifacts:
- path: plumed2-win-build
- path: plumed2-win-build\bin\plumed.exe
