version: '{branch}-{build}'
image: Visual Studio 2017
clone_depth: 0
clone_script:
- cmd: |
    cd
    git clone -q --depth=5 --branch=v2.3.2 git://github.com/plumed/plumed2.git plumed2-git
build_script:
- cmd: |
    choco install mingw
    refreshenv
    cd plumed2-git    
    g++ -v
    bash ./configure --disable-shared LDFLAGS="-static -s" --prefix=/c/projects/plumed2-appveyor/plumed2-win-build
    make -j2
    make install
test_script:
- cmd: |
    set PATH=C:\projects\plumed2-appveyor\plumed2-win-build\bin;%PATH%
    cd regtest
    make -j2
artifacts:
- path: plumed2-win-build
- path: plumed2-win-build\bin\plumed.exe
