version: '{branch}-{build}'
image: Visual Studio 2015
clone_depth: 0
clone_script:
- cmd: |
    cd
    git clone -q --depth=1 --branch=v2.3.2 git://github.com/plumed/plumed2.git plumed2-git
build_script:
- cmd: |
    cd plumed2-git
    rem set mw=C:\msys64\usr\bin
    set mw=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
    rem dir /s %mw%
    set PATH=%mw%;%PATH%
    rem dir /s %mw%
    g++ -v
    bash ./configure --disable-shared CFLAGS="-fpermissive" LDFLAGS="-static -s" --prefix=/c/projects/plumed2-appveyor/plumed2-win-build
    mingw32-make -j2
    make install
test_script:
- cmd: |
    set PATH=C:\projects\plumed2-appveyor\plumed2-win-build\bin;%PATH%
    cd regtest
    make -j2
artifacts:
- path: plumed2-win-build
- path: plumed2-win-build\bin\plumed.exe
